

@host = localhost
@port = 4000
@mount = api

@version = v2

@apihost = http://{{ host }}:{{ port }}

@baseurl = {{apihost}}/{{ mount }}/{{ version }}

### Healthcheck
GET {{ baseurl }}

### auth


POST {{ baseurl }}/auth
Content-Type: application/json

{"userId":"123"}


### rest with anon key

GET http://localhost:8000/rest/v1/
apikey: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTYwMzk2ODgzNCwiZXhwIjoyNTUwNjUzNjM0LCJyb2xlIjoiYW5vbiJ9.36fUebxgx1mcBo4s19v0SzqmzunP--hm_hep0uLX0ew


### rest with service role key
GET http://localhost:8000/rest/v1/
apikey: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTYwMzk2ODgzNCwiZXhwIjoyNTUwNjUzNjM0LCJyb2xlIjoic2VydmljZV9yb2xlIn0.necIJaiP7X2T2QjGeV-FhpkizcNTX8HjDDBAxpgQTEI
